/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GatechangeRouteImport } from './routes/gatechange'
import { Route as DisplaysRouteImport } from './routes/displays'
import { Route as CountersRouteImport } from './routes/counters'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BoardingRouteImport } from './routes/boarding'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GatechangeRoute = GatechangeRouteImport.update({
  id: '/gatechange',
  path: '/gatechange',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplaysRoute = DisplaysRouteImport.update({
  id: '/displays',
  path: '/displays',
  getParentRoute: () => rootRouteImport,
} as any)
const CountersRoute = CountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingRoute = BoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boarding': typeof BoardingRoute
  '/checkin': typeof CheckinRoute
  '/complaints': typeof ComplaintsRoute
  '/counters': typeof CountersRoute
  '/displays': typeof DisplaysRoute
  '/gatechange': typeof GatechangeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boarding': typeof BoardingRoute
  '/checkin': typeof CheckinRoute
  '/complaints': typeof ComplaintsRoute
  '/counters': typeof CountersRoute
  '/displays': typeof DisplaysRoute
  '/gatechange': typeof GatechangeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/boarding': typeof BoardingRoute
  '/checkin': typeof CheckinRoute
  '/complaints': typeof ComplaintsRoute
  '/counters': typeof CountersRoute
  '/displays': typeof DisplaysRoute
  '/gatechange': typeof GatechangeRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/boarding'
    | '/checkin'
    | '/complaints'
    | '/counters'
    | '/displays'
    | '/gatechange'
    | '/inbox'
    | '/login'
    | '/search'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/boarding'
    | '/checkin'
    | '/complaints'
    | '/counters'
    | '/displays'
    | '/gatechange'
    | '/inbox'
    | '/login'
    | '/search'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/boarding'
    | '/checkin'
    | '/complaints'
    | '/counters'
    | '/displays'
    | '/gatechange'
    | '/inbox'
    | '/login'
    | '/search'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BoardingRoute: typeof BoardingRoute
  CheckinRoute: typeof CheckinRoute
  ComplaintsRoute: typeof ComplaintsRoute
  CountersRoute: typeof CountersRoute
  DisplaysRoute: typeof DisplaysRoute
  GatechangeRoute: typeof GatechangeRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gatechange': {
      id: '/gatechange'
      path: '/gatechange'
      fullPath: '/gatechange'
      preLoaderRoute: typeof GatechangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/displays': {
      id: '/displays'
      path: '/displays'
      fullPath: '/displays'
      preLoaderRoute: typeof DisplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counters': {
      id: '/counters'
      path: '/counters'
      fullPath: '/counters'
      preLoaderRoute: typeof CountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding': {
      id: '/boarding'
      path: '/boarding'
      fullPath: '/boarding'
      preLoaderRoute: typeof BoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BoardingRoute: BoardingRoute,
  CheckinRoute: CheckinRoute,
  ComplaintsRoute: ComplaintsRoute,
  CountersRoute: CountersRoute,
  DisplaysRoute: DisplaysRoute,
  GatechangeRoute: GatechangeRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
